<?php

namespace Tests\Feature\Http\Controllers\Api;

use App\Http\Resources\CategoryResource;
use App\Models\Category;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Testing\TestResponse;
use Tests\Traits\TestResources;
use Tests\Traits\TestSaves;
use Tests\Traits\TestValidations;
use Tests\TestCase;

class CategoryControllerTest extends TestCase
{
    use DatabaseMigrations, TestValidations, TestSaves, TestResources;

    protected $category;
    protected $serializedFields = [
        'id',
        'name',
        'description',
        'is_active',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->category = Category::factory()->create();
    }

    public function testInvalidationData()
    {
        $data = [
            'name' => ''
        ];
        $this->assertInvalidationInStoreAction($data, $this->validRequired);
        $this->assertInvalidationInUpdateAction($data, $this->validRequired);

        $data = [
            'name' => str_repeat('a', 256)
        ];
        $this->assertInvalidationInStoreAction($data, $this->validMax, $this->limitMax);
        $this->assertInvalidationInUpdateAction($data, $this->validMax, $this->limitMax);

        $data = [
            'is_active' => 'a'
        ];
        $this->assertInvalidationInStoreAction($data, $this->validBool);
        $this->assertInvalidationInUpdateAction($data, $this->validBool);
    }

    public function testStore()
    {
        $data = [
            'name' => 'test'
        ];
        $response = $this->assertStore($data, $data + ['description' => null, 'is_active' => true, 'deleted_at' => null]);
        $this->assertResourceValid($response);

        $data = [
            'name' => 'teste',
            'description' => 'description_test',
            'is_active' => false
        ];
        $response = $this->assertStore($data, $data + ['deleted_at' => null]);
        $this->assertResourceValid($response);
    }

    public function testUpdate()
    {
        $this->category = Category::factory()->create([
            'description' => 'description',
            'is_active' => false
        ]);

        $data = [
            'name' => 'teste',
            'description' => null,
            'is_active' => true
        ];
        $response = $this->assertUpdate($data, $data + ['deleted_at' => null]);
        $this->assertResourceValid($response);

        $data = [
            'name' => 'teste',
            'description' => ''
        ];
        $this->assertUpdate($data, array_merge($data, ['description' => null]));

        $data['description'] = 'test';
        $this->assertUpdate($data, array_merge($data, ['description' => 'test']));

        $data['description'] = null;
        $this->assertUpdate($data, array_merge($data, ['description' => null]));
    }

    public function testDestroy()
    {
        $response = $this->json('DELETE', route('api.categories.destroy', $this->category->id));

        $response
            ->assertStatus(204);

        self::assertNull(Category::find($this->category->id));
        self::assertNotNull(Category::withTrashed()->find($this->category->id));
    }

    protected function getRouteIndex()
    {
        return route('api.categories.index');
    }

    protected function getRouteShow()
    {
        return route('api.categories.show', $this->category->id);
    }

    protected function getRouteStore()
    {
        return route('api.categories.store');
    }

    protected function getRouteUpdate()
    {
        return route('api.categories.update', $this->category->id);
    }

    protected function getModel()
    {
        return Category::class;
    }

    protected function getModelItem()
    {
        return $this->category;
    }

    protected function getSerializedFields()
    {
        return $this->serializedFields;
    }

    protected function getResourceCollection(): string
    {
        return $this->getResource();
    }

    protected function getResource(): string
    {
        return CategoryResource::class;
    }
}
